// 试题类型
export const QUESTION_TYPE_SINGLE_CHOICE = '1' // 单选题
export const QUESTION_TYPE_MULTIPLE_CHOICE = '2' // 多选题
export const QUESTION_TYPE_JUDGEMENT = '3' // 判断题
export const QUESTION_TYPE_BLANK = '4' // 填空题
export const QUESTION_TYPE_SHORT_ANSWER = '5' // 简答题
export const QUESTION_TYPE_LISTENING = '6' // 听力题
export const QUESTION_TYPE_COMPREHENSIVE = '7' // 综合题
export const QUESTION_TYPE_LINE = '8' // 连线题
export const QUESTION_TYPE_FOLLOW_READ = '9' // 跟读题
export const QUESTION_TYPE_SELECT_BLANK = '10' // 选填题
export const QUESTION_TYPE_SORT = '11' // 排序题
export const QUESTION_TYPE_CLASSIFICATION = '12' // 归类题
export const QUESTION_TYPE_LEVEL_LABEL_UNCERTAIN_CHOICE = '52' // 不定项选择题

// 是否收藏
export const QUESTION_UNCOLLECTED = '0'
export const QUESTION_COLLECTED = '1'

// 客观题类型
export const QUESTION_IS_OBJECTIVE_TYPES = [
  QUESTION_TYPE_SINGLE_CHOICE,
  QUESTION_TYPE_MULTIPLE_CHOICE,
  QUESTION_TYPE_JUDGEMENT,
  QUESTION_TYPE_LINE
]

// 单选题，判断题 ，多选题
export const ODD_MUCH_JUDGE_TYPES = [
  // QUESTION_TYPE_SINGLE_CHOICE, // 单选
  // QUESTION_TYPE_MULTIPLE_CHOICE, // 多选
  QUESTION_TYPE_JUDGEMENT // 判断
]

// 主观题类型
export const QUESTION_IS_SUBJECTIVE_TYPES = [
  QUESTION_TYPE_BLANK,
  QUESTION_TYPE_SHORT_ANSWER,
  QUESTION_TYPE_SELECT_BLANK
]

// 扫描作业主观题类型(包括连线题)
export const QUESTION_SUBJECTIVE_TYPES = [
  QUESTION_TYPE_BLANK,
  QUESTION_TYPE_SHORT_ANSWER,
  QUESTION_TYPE_SELECT_BLANK,
  QUESTION_TYPE_LINE
]

// 选择题类型
export const QUESTION_IS_CHOICE_TYPES = [
  QUESTION_TYPE_SINGLE_CHOICE,
  QUESTION_TYPE_MULTIPLE_CHOICE,
  QUESTION_TYPE_JUDGEMENT,
  QUESTION_TYPE_LEVEL_LABEL_UNCERTAIN_CHOICE
]

// 如果为综合类题型
export const QUESTION_IS_COMPREHENSIVE_TYPES = [
  QUESTION_TYPE_LISTENING,
  QUESTION_TYPE_COMPREHENSIVE
]

// 文本类题型
export const QUESTION_IS_TEXT_TYPES = [
  QUESTION_TYPE_BLANK,
  QUESTION_TYPE_SHORT_ANSWER,
  QUESTION_TYPE_SELECT_BLANK
]

// 填空类题型
export const QUESTION_IS_BLANK_TYPES = [
  QUESTION_TYPE_BLANK,
  QUESTION_TYPE_SELECT_BLANK
]

// 有附件类题型: 简答题与跟读题
export const QUESTION_HAVE_ATTATCHMENTS = [
  QUESTION_TYPE_SHORT_ANSWER,
  QUESTION_TYPE_FOLLOW_READ
]

// 试题难度
export const QUESTION_DEGREE_EASIER = 0.1
export const QUESTION_DEGREE_EASY = 0.3
export const QUESTION_DEGREE_MEDIUM = 0.5
export const QUESTION_DEGREE_HARD = 0.7
export const QUESTION_DEGREE_HARDER = 0.9

// 试题作答结果
export const QUESTION_ANSWER_WRONG = '1'
export const QUESTION_ANSWER_RIGHT = '2'
export const QUESTION_ANSWER_HALFRIGHT = '3'
export const QUESTION_ANSWER_HALFRIGHT_WEB = '4' // web端半对半错为4
export const QUESTION_RESULT_NOCORRECT = '3'

// 试题错误原因
export const QUESTION_WRONG_TITLE = '1'
export const QUESTION_WRONG_ANSWER = '2'
export const QUESTION_WRONG_ANALYSIS = '3'
export const QUESTION_WRONG_KNOWLEDGE = '4'
export const QUESTION_WRONG_SELFTYPE = '5'
export const QUESTION_WRONG_DEGREE = '6'
export const QUESTION_WRONG_OTHER = '7'
